/**
 * useSpeciesIcons — Runtime composable for loading and serving
 * species-to-Game-Icons-Iconify mappings generated at SSG build time.
 *
 * The mapping file (species-icon-mapping.json) is generated by:
 *   node scripts/build-species-icon-mapping.mjs
 *
 * This runs at build time in GitHub Actions and outputs a static JSON
 * file consumed at runtime by this composable and by the marker system.
 */

import { ref, readonly } from 'vue'
import type { SpeciesIconMapping, SpeciesIconMatch } from '@/lib/game-icons-map'

const MAPPING_PATH = '/data/species/species-icon-mapping.json'

let cachedMapping: SpeciesIconMapping | null = null

async function loadMapping(baseURL?: string): Promise<SpeciesIconMapping> {
  if (cachedMapping) return cachedMapping
  const prefix = baseURL && baseURL !== '/' ? baseURL : ''
  const url = `${prefix}${MAPPING_PATH}`
  try {
    const res = await fetch(url)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    cachedMapping = await res.json() as SpeciesIconMapping
    return cachedMapping
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn('[useSpeciesIcons] Failed to load mapping:', err)
    return {}
  }
}

export function useSpeciesIcons(baseURL?: string) {
  const mapping = ref<SpeciesIconMapping>({})
  const loading = ref(true)
  const error = ref<Error | null>(null)

  async function init() {
    try {
      loading.value = true
      mapping.value = await loadMapping(baseURL)
    } catch (e) {
      error.value = e as Error
    } finally {
      loading.value = false
    }
  }

  function getIcon(speciesId: string): SpeciesIconMatch | undefined {
    return mapping.value[speciesId]
  }

  function getIconifyName(speciesId: string): string | undefined {
    return mapping.value[speciesId]?.iconifyName
  }

  function getIconSvgUrl(speciesId: string): string | undefined {
    const match = mapping.value[speciesId]
    if (!match) return undefined
    // Iconify API URL to fetch SVG inline
    return `https://api.iconify.design/${match.iconifyName.replace(':', '/')}.svg`
  }

  return {
    mapping: readonly(mapping),
    loading: readonly(loading),
    error: readonly(error),
    init,
    getIcon,
    getIconifyName,
    getIconSvgUrl,
  }
}
